# Site wide configuration

title: CC Korea 제 3 회 국제 컨퍼런스 2014
title_en: 2014 CC KOREA International Conference
description: The Third conference of Creative Commons Korea
logo: cck-logo.png
teaser: mainbanner.png
locale: ko_KR
locale_alt: en_US
url: http://2014con.cckorea.org
feature_img: after-banner.jpg

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Creative Commons Korea
  email: creative@cckorea.org
  twitter: cckorea
  google:
    ad-client:
    ad-slot:
    analytics: UA-54013301-1
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


collections:
  program:
    output: true
    permalink: /program/:path/

defaults:
  -
    scope:
      path: "program"
      type: "program" # a collection in your site, in plural form
    values:
      layout: "program"
